#!/usr/bin/env sh

# Exit if any subcommand fails
set -e

# Set up Ruby dependencies via Bundler
bundle install

# Set up the database
bundle exec rake db:setup

# Add binstubs to PATH via export PATH=".git/safe/../../bin:$PATH" in ~/.zshenv
mkdir -p .git/safe

# Set up configurable environment variables
if [ ! -f .env ]; then
  cp .sample.env .env
fi

# Pick a port for Foreman
echo "port: 7000" > .foreman